In [6]:

# Import Libraries

import pandas as pd

# Load Datasets

customers = pd.read_csv(r"H:\DA projects\project_2\data_set\customers.csv")
orders = pd.read_csv(r"H:\DA projects\project_2\data_set\orders.csv")
order_items = pd.read_csv(r"H:\DA projects\project_2\data_set\order_items.csv")
products = pd.read_csv(r"H:\DA projects\project_2\data_set\products.csv")

In [7]:
# Preview First 5 Rows of Each Dataset

print(customers.head())
print(orders.head())
print(order_items.head())
print(products.head())

   customer_id signup_date state acquisition_channel
0            1  2024-09-13    CO      organic_search
1            2  2025-10-21    IL         paid_search
2            3  2025-01-17    AZ            referral
3            4  2024-06-23    FL         paid_social
4            5  2025-04-08    IL         paid_social
   order_id  customer_id           order_date     status payment_method  \
0    100001         1530  2024-01-01 09:24:45  completed    credit_card
1    100002         3531  2024-01-01 10:37:49  completed    credit_card
2    100003          840  2024-01-01 10:59:09  completed    credit_card
3    100004          725  2024-01-01 12:48:34  completed      apple_pay
4    100005         3452  2024-01-01 17:44:03  completed      gift_card

  discount_code  shipping_fee
0           NaN          6.95
1           NaN          0.00
2           NaN          0.00
3     WELCOME10          0.00
4           NaN          0.00
   order_id  product_id  quantity  unit_price  discount_amount
0    100001        1031         1       38.99              0.0
1    100002        1087         1       45.99              0.0
2    100002        1072         1      141.99              0.0
3    100003        1048         1      139.99              0.0
4    100004        1083         1       19.99              2.0
   product_id            product_name  category  list_price  unit_cost
0        1001        Brass Chef Knife   Kitchen       61.99      38.13
1        1002    Walnut Cutting Board   Kitchen      138.99      74.76
2        1003  Matte Black Dutch Oven   Kitchen       22.99      13.50
3        1004         Classic Skillet   Kitchen       75.99      39.86
4        1005   Linen Mixing Bowl Set  Kitchen        79.99      41.11

In [8]:
# Customers Dataset Information

customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          3600 non-null   int64
 1   signup_date          3600 non-null   object
 2   state                3600 non-null   object
 3   acquisition_channel  3600 non-null   object
dtypes: int64(1), object(3)
memory usage: 112.6+ KB

In [9]:
# Orders Dataset Information

orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9245 entries, 0 to 9244
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        9245 non-null   int64
 1   customer_id     9245 non-null   int64
 2   order_date      9245 non-null   object
 3   status          9245 non-null   object
 4   payment_method  9245 non-null   object
 5   discount_code   1411 non-null   object
 6   shipping_fee    9245 non-null   float64
dtypes: float64(1), int64(2), object(4)
memory usage: 505.7+ KB

In [10]:
# order items Dataset Information
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15608 entries, 0 to 15607
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         15608 non-null  int64
 1   product_id       15608 non-null  int64
 2   quantity         15608 non-null  int64
 3   unit_price       15409 non-null  float64
 4   discount_amount  15608 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 609.8 KB

In [11]:
# products Dataset Information
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    90 non-null     int64
 1   product_name  90 non-null     object
 2   category      90 non-null     object
 3   list_price    90 non-null     float64
 4   unit_cost     90 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 3.6+ KB

In [12]:
# produts Dataset Information
products["category"].unique()

array(['Kitchen', ' Kitchen', 'Kitchen ', 'kitchen', 'KITCHEN',
       ' Bedding', 'Bedding', 'bedding', 'BEDDING', 'Bath', 'bath',
       'Furniture', 'Furniture ', 'furniture', 'FURNITURE', 'Lighting',
       'LIGHTING', 'Outdoor', 'OUTDOOR', ' Outdoor', 'Decor', 'decor',
       'Storage', 'Storage '], dtype=object)

In [13]:
# Standardize Product Categories
products["category"] = (products["category"].str.strip().str.title())

In [14]:
# Check Unique Product Categories

products["category"].unique()

array(['Kitchen', 'Bedding', 'Bath', 'Furniture', 'Lighting', 'Outdoor',
       'Decor', 'Storage'], dtype=object)

In [15]:
# Convert Date Columns
customers["signup_date"] = pd.to_datetime(customers["signup_date"])
orders["order_date"] = pd.to_datetime(orders["order_date"])

In [16]:
# Verify Dataset Structure and Data Types
customers.info()
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          3600 non-null   int64
 1   signup_date          3600 non-null   datetime64[ns]
 2   state                3600 non-null   object
 3   acquisition_channel  3600 non-null   object
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 112.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9245 entries, 0 to 9244
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        9245 non-null   int64
 1   customer_id     9245 non-null   int64
 2   order_date      9245 non-null   datetime64[ns]
 3   status          9245 non-null   object
 4   payment_method  9245 non-null   object
 5   discount_code   1411 non-null   object
 6   shipping_fee    9245 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 505.7+ KB

In [17]:
# Check for Duplicate Records
print("Customers:", customers.duplicated().sum())
print("Orders:", orders.duplicated().sum())
print("Order Items:", order_items.duplicated().sum())
print("Products:", products.duplicated().sum())

Customers: 0
Orders: 38
Order Items: 0
Products: 0

In [18]:
# Remove Duplicate Records
orders = orders.drop_duplicates()

In [19]:
# Verify Duplicate Removal
orders.duplicated().sum()

np.int64(0)

In [20]:

# Missing Value Analysis
print(customers.isnull().sum())
print()

print(orders.isnull().sum())
print()

print(order_items.isnull().sum())
print()

print(products.isnull().sum())

customer_id            0
signup_date            0
state                  0
acquisition_channel    0
dtype: int64

order_id             0
customer_id          0
order_date           0
status               0
payment_method       0
discount_code     7802
shipping_fee         0
dtype: int64

order_id             0
product_id           0
quantity             0
unit_price         199
discount_amount      0
dtype: int64

product_id      0
product_name    0
category        0
list_price      0
unit_cost       0
dtype: int64

In [21]:
# Inspect Missing Unit Price Records
order_items[order_items["unit_price"].isnull()].head()

     order_id  product_id  quantity  unit_price  discount_amount
55     100033        1086         1         NaN              0.0
110    100062        1020         1         NaN              0.0
197    100116        1087         2         NaN              0.0
366    100210        1014         1         NaN              0.0
626    100361        1077         1         NaN              0.0

In [22]:
# Check Remaining Missing Unit Prices
order_items["unit_price"].isnull().sum()

np.int64(199)

In [23]:
# Merge Product Price Information
order_items = order_items.merge(
    products[['product_id', 'list_price']],
    on='product_id',
    how='left'
)

In [24]:
# Preview Order Items Dataset
order_items.head()

   order_id  product_id  quantity  unit_price  discount_amount  list_price
0    100001        1031         1       38.99              0.0       38.99
1    100002        1087         1       45.99              0.0       45.99
2    100002        1072         1      141.99              0.0      141.99
3    100003        1048         1      139.99              0.0      139.99
4    100004        1083         1       19.99              2.0       19.99

In [25]:
# Impute Missing Unit Prices
order_items["unit_price"] = order_items["unit_price"].fillna(
    order_items["list_price"])

In [26]:
# Verify Missing Unit Price Values
order_items["unit_price"].isnull().sum()

np.int64(0)

In [27]:
# Remove Temporary Column
order_items.drop(
    columns=["list_price"],
    inplace=True
)

In [28]:
# Merge Datasets
df = (
    orders
    .merge(customers, on="customer_id")
    .merge(order_items, on="order_id")
    .merge(products, on="product_id")
)

In [40]:
# Check Shape of Merged Dataset
df.shape

(15608, 18)

In [44]:
df.drop(
    columns=["list_price"],
    inplace=True
)

In [45]:
# Preview Master Dataset
df.head()

,order_id,customer_id,order_date,status,payment_method,discount_code,shipping_fee,signup_date,state,acquisition_channel,product_id,quantity,unit_price,discount_amount,product_name,category,unit_cost
0,100001,1530,2024-01-01 09:24:45,completed,credit_card,NaN,6.95,2023-12-30,AZ,organic_search,1031,1,38.99,0.0,Stoneware Soap Dispenser,Bath,20.19
1,100002,3531,2024-01-01 10:37:49,completed,credit_card,NaN,0.00,2023-11-19,VA,organic_search,1087,1,45.99,0.0,Cotton Pantry Container Set,Storage,20.30
2,100002,3531,2024-01-01 10:37:49,completed,credit_card,NaN,0.00,2023-11-19,VA,organic_search,1072,1,141.99,0.0,Coastal Picture Frame Set,Decor,62.78
3,100003,840,2024-01-01 10:59:09,completed,credit_card,NaN,0.00,2023-10-30,MN,organic_search,1048,1,139.99,0.0,Linen Loveseat,Furniture,71.41
4,100004,725,2024-01-01 12:48:34,completed,apple_pay,WELCOME10,0.00,2023-08-20,MI,paid_search,1083,1,19.99,2.0,Velvet Drawer Organizer,Storage,9.51

In [ ]:
#connect to the sql
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in e:\python314\lib\site-packages (2.1.3)
Requirement already satisfied: pymysql in e:\python314\lib\site-packages (1.2.3)
Requirement already satisfied: typing-extensions>=4.6.0 in e:\python314\lib\site-packages (from sqlalchemy) (4.16.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: E:\Python314\python.exe -m pip install --upgrade pip

In [47]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Nithushana*09@localhost/ecommerce_analysis"
)

df.to_sql(
    "ecommerce_master",
    con=engine,
    if_exists="replace",
    index=False
)

15608

In [48]:
with engine.connect() as conn:
    print("Connected Successfully")

Connected Successfully

In [49]:
df.to_csv("ecommerce_master.csv", index=False)